### ISSUE TITLE
EmbeddedPostgres is not a constructor

### ISSUE THREAD

**Issue by xthanhx** [leinelissen/embedded-postgres#2]
I liked introducing it on the Readme and got an error like the one below.
![Screenshot 2023-04-13 at 15 21 14](https://user-images.githubusercontent.com/63955571/231699554-35ba5a64-39e7-431d-945e-ebbfe4b51693.png)

but when I do like the below it works.
![Screenshot 2023-04-13 at 15 23 26](https://user-images.githubusercontent.com/63955571/231700010-2f02fcbc-c80b-43d8-81fd-5da3a23f49e6.png)

![Screenshot 2023-04-13 at 15 23 51](https://user-images.githubusercontent.com/63955571/231700035-ae439c5c-915e-4e17-8f45-9e773f222246.png)

**Comment by leinelissen** [comment]
Hey @xthanhx, thanks for reporting the issue, I managed to reproduce it. The problem is with how Typescript compiles ESM to CJS modules. I have made a small change, which now results in the right export qualifier (`module.exports`). That release is on its way to NPM, and you should be able to install it with `npm i embedded-postgres@latest`. You should then be able to import the package with `import EmbeddedPostgres from 'embedded-postgres';` as expected.
